<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="7.0.0-preview.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PrimeNGTableExtension\PrimeNGTableExtension.csproj" />
    <ProjectReference Include="..\FPLCompanion.DataService\FPLCompanion.DataService.csproj" />
    <ProjectReference Include="..\FPLCompanion.Dependencies\FPLCompanion.Dependencies.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Requests\Player\Commands\" />
  </ItemGroup>

</Project>
